<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FlaUI.UIA3" Version="4.0.0" />
    <PackageReference Include="Microsoft.Office.Interop.Word" Version="15.0.4797.1004" />
  </ItemGroup>
</Project>
